//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoTester.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AutoTester.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap AutoTester {
            get {
                object obj = ResourceManager.GetObject("AutoTester", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap Button_Close {
            get {
                object obj = ResourceManager.GetObject("Button_Close", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap Button_Close_Hover {
            get {
                object obj = ResourceManager.GetObject("Button_Close_Hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap Button_LeftArrow {
            get {
                object obj = ResourceManager.GetObject("Button_LeftArrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap Button_LeftArrow_Hover_ {
            get {
                object obj = ResourceManager.GetObject("Button_LeftArrow_Hover_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap Button_Minus {
            get {
                object obj = ResourceManager.GetObject("Button_Minus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap Button_Minus_Hover_ {
            get {
                object obj = ResourceManager.GetObject("Button_Minus_Hover_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap Button_Plus {
            get {
                object obj = ResourceManager.GetObject("Button_Plus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap Button_Plus_Hover_ {
            get {
                object obj = ResourceManager.GetObject("Button_Plus_Hover_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap Button_RightArrow {
            get {
                object obj = ResourceManager.GetObject("Button_RightArrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap Button_RightArrow_Hover_ {
            get {
                object obj = ResourceManager.GetObject("Button_RightArrow_Hover_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap MainSnap {
            get {
                object obj = ResourceManager.GetObject("MainSnap", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap Tester {
            get {
                object obj = ResourceManager.GetObject("Tester", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap TesterPNG {
            get {
                object obj = ResourceManager.GetObject("TesterPNG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   {\rtf1\adeflang1025\ansi\ansicpg949\uc2\adeff0\deff0\stshfdbch31505\stshfloch31506\stshfhich31506\stshfbi0\deflang1033\deflangfe1042\themelang1033\themelangfe1042\themelangcs0{\fonttbl{\f0\fbidi \froman\fcharset0\fprq2{\*\panose 02020603050405020304}Times New Roman;}
        ///{\f20\fbidi \fmodern\fcharset129\fprq2{\*\panose 020b0600000101010101}\&apos;b1\&apos;bc\&apos;b8\&apos;b2{\*\falt Gulim};}{\f20\fbidi \fmodern\fcharset129\fprq2{\*\panose 020b0600000101010101}\&apos;b1\&apos;bc\&apos;b8\&apos;b2{\*\falt Gulim};}
        ///{\f36\fbidi \fmodern\fcharset129\fp[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string 도움말_홈 {
            get {
                return ResourceManager.GetString("도움말_홈", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {\rtf1\adeflang1025\ansi\ansicpg949\uc2\adeff0\deff0\stshfdbch31505\stshfloch31506\stshfhich31506\stshfbi0\deflang1033\deflangfe1042\themelang1033\themelangfe1042\themelangcs0{\fonttbl{\f0\fbidi \froman\fcharset0\fprq2{\*\panose 02020603050405020304}Times New Roman;}
        ///{\f20\fbidi \fmodern\fcharset129\fprq2{\*\panose 020b0600000101010101}\&apos;b1\&apos;bc\&apos;b8\&apos;b2{\*\falt Gulim};}{\f20\fbidi \fmodern\fcharset129\fprq2{\*\panose 020b0600000101010101}\&apos;b1\&apos;bc\&apos;b8\&apos;b2{\*\falt Gulim};}
        ///{\f38\fbidi \fmodern\fcharset129\fp[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string 메뉴_표시줄 {
            get {
                return ResourceManager.GetString("메뉴_표시줄", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {\rtf1\adeflang1025\ansi\ansicpg949\uc2\adeff0\deff0\stshfdbch31505\stshfloch31506\stshfhich31506\stshfbi0\deflang1033\deflangfe1042\themelang1033\themelangfe1042\themelangcs0{\fonttbl{\f0\fbidi \froman\fcharset0\fprq2{\*\panose 02020603050405020304}Times New Roman;}
        ///{\f20\fbidi \fmodern\fcharset129\fprq2{\*\panose 020b0600000101010101}\&apos;b1\&apos;bc\&apos;b8\&apos;b2{\*\falt Gulim};}{\f20\fbidi \fmodern\fcharset129\fprq2{\*\panose 020b0600000101010101}\&apos;b1\&apos;bc\&apos;b8\&apos;b2{\*\falt Gulim};}
        ///{\f38\fbidi \fmodern\fcharset129\fp[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string 이벤트_집합과_워크플로우 {
            get {
                return ResourceManager.GetString("이벤트_집합과_워크플로우", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {\rtf1\adeflang1025\ansi\ansicpg949\uc2\adeff0\deff0\stshfdbch31505\stshfloch31506\stshfhich31506\stshfbi0\deflang1033\deflangfe1042\themelang1033\themelangfe1042\themelangcs0{\fonttbl{\f0\fbidi \froman\fcharset0\fprq2{\*\panose 02020603050405020304}Times New Roman;}
        ///{\f20\fbidi \fmodern\fcharset129\fprq2{\*\panose 020b0600000101010101}\&apos;b1\&apos;bc\&apos;b8\&apos;b2{\*\falt Gulim};}{\f20\fbidi \fmodern\fcharset129\fprq2{\*\panose 020b0600000101010101}\&apos;b1\&apos;bc\&apos;b8\&apos;b2{\*\falt Gulim};}
        ///{\f36\fbidi \fmodern\fcharset129\fp[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string 키_입력_도움말 {
            get {
                return ResourceManager.GetString("키_입력_도움말", resourceCulture);
            }
        }
    }
}
